server.port=8083
spring.application.name=social-service

spring.data.mongodb.uri=${MONGODB_URI:mongodb+srv://kanchuganesh789:Master%40123@nursery.7amnd.mongodb.net/ces_social?retryWrites=true&w=majority&appName=nursery}
